        !COMPILER-GENERATED INTERFACE MODULE: Wed Dec 29 21:44:50 2021
        MODULE OUTPUTDATA__genmod
          INTERFACE 
            SUBROUTINE OUTPUTDATA(ET,NTARG,NCENT)
              REAL(KIND=8) :: ET
              INTEGER(KIND=4) :: NTARG
              INTEGER(KIND=4) :: NCENT
            END SUBROUTINE OUTPUTDATA
          END INTERFACE 
        END MODULE OUTPUTDATA__genmod
