        !COMPILER-GENERATED INTERFACE MODULE: Wed Dec 29 19:27:17 2021
        MODULE TIMESTAMP__genmod
          INTERFACE 
            SUBROUTINE TIMESTAMP
            END SUBROUTINE TIMESTAMP
          END INTERFACE 
        END MODULE TIMESTAMP__genmod
